### ISSUE TITLE
redundant results and insertion variants recording

### ISSUE THREAD

**Issue by biozzq** [kcleal/dysgu#25] opened 2022-02-10 15:11 UTC
Dear @kcleal 

I have several questions about the output of dysgu, hope you can take some time to help me. Thank you in advance.

First, I found the result of dysgu is redundant, for example, the following deletion can be merged, in my opinion.
```
1       1136857 78530   C       <DEL>   .       PASS    SVMETHOD=DYSGUv1.3.5;SVTYPE=DEL;END=1136943;CHR2=1;GRP=2350686;NGRP=1;CT=5to3;CIPOS95=0;CIEND95=0;SVLEN=86;CONTIGB=gcggggtttattctaagaatgattatttccCATAATTCCTGGTCCTGTGTGAGTGCCAGCCACCGTTTCCTCGTGTCCCTCTGGATGGGTCATTCCCTGGCCTCTGGCCTGTGTGCTGACCAGTCctgagcggccct;KIND=intra_regional;GC=55.47;NEXP=0;STRIDE=0;EXPSEQ;RPOLY=0;OL=0;SU=3;WR=0;PE=0;SR=0;SC=3;BND=3;LPREC=0;RT=pe      GT:GQ:MAPQP:SU:WR:PE:SR:SC:BND:COV:NEIGH10:PS:MS:RMS:RED:BCC:FCC:ICN:OCN:PROB   0/1:66:60:3:0:0:0:3:3:16.89:0:1:2:54:0:0:0.938:0.789:0.842:0.559
1       1136860 78532   C       <DEL>   .       PASS    SVMETHOD=DYSGUv1.3.5;SVTYPE=DEL;END=1136945;CHR2=1;GRP=1565924;NGRP=1;CT=3to5;CIPOS95=0;CIEND95=0;SVLEN=85;CONTIGA=GTTAATTTGCTTGCAAGAAGTTTGAGCCTTTCTGGTCTCGCTTTTACGATGCATTGAAAGTGAGCCTGGAGCGGGGTTTATTCTAAGAATGATTATTTCCCAtaattcctggtcctgtgtgagtgccagccaccgtttcctcgtgtccctctgg;KIND=intra_regional;GC=46.75;NEXP=0;STRIDE=0;EXPSEQ;RPOLY=0;OL=0;SU=6;WR=0;PE=0;SR=0;SC=6;BND=6;LPREC=0;RT=pe     GT:GQ:MAPQP:SU:WR:PE:SR:SC:BND:COV:NEIGH10:PS:MS:RMS:RED:BCC:FCC:ICN:OCN:PROB   0/1:28:60:6:0:0:0:6:6:16.89:0:0:6:76:28:0:0.938:0.789:0.842:0.572
```
Second, I found that REF allele was not identical with the reference sequence allele at that POS

Finally, for the insertion, in my mind, the END tag should be the same with POS, however, they are different in the output, for example,
```
1       8058312 59      G       TAGCTAGCTAGCTAGCTAGATCTATAAATAGATAGATAG .       PASS    SVMETHOD=DYSGUv1.3.5;SVTYPE=INS;END=8058322;CHR2=1;GRP=2400;NGRP=1;CT=5to3;CIPOS95=0;CIEND95=0;SVLEN=40;KIND=extra-regional;GC=32.03;NEXP=0;STRIDE=0;EXPSEQ;RPOLY=42;OL=0;SU=13;WR=0;PE=1;SR=3;SC=12;BND=9;LPREC=0;RT=pe        GT:GQ:MAPQP:SU:WR:PE:SR:SC:BND:COV:NEIGH10:PS:MS:RMS:RED:BCC:FCC:ICN:OCN:PROB   0/1:147:60:13:0:1:3:12:9:16.65:0:11:6:0:0:13:0.655:1.526:1:0.627
```

Sincerely,
Zheng zhuqing

**Comment by kcleal** [comment] 2022-02-10 15:40
Hi Zheng, these are all good points, thanks for reporting them.

I agree with the first point these look like they should be merged. The reason for failure to merge I think is because the first contig has soft-clipped bases at both ends, dysgu is a bit over cautious with these. I will see if I can fix this type of error.

For the second point, I have a few ideas where this could be going wrong. I will see if I can find the error myself.

For the third point, I think this is by design. It looks like this event was inferred from split-read mappings SR=3, so might be a small tandem duplication (a class of insertion), so the start and end coordinates indicate a duplicated fragment.

**Comment by kcleal** [comment] 2022-02-15 19:55
I have added a patch to address the bugs raised. The latest version (1.3.6) should now merge the example DEL event, and should provide the correct REF base in the output. I will try and push the release to pypi in the next few days

**Comment by kcleal** [comment] 2022-03-21 10:20
v1.3.7 Should hopefully address these points. Closing for now.

**Closed by kcleal** 2022-03-21 10:20 UTC
Labels: bug
